- name: Setup my Ubuntu
  hosts: localhost
  vars:
    sshs:
      - { source_key: './.ssh/ansible_id_rsa', dest_key: "{{ lookup('env', 'HOME') }}/.ssh/ansible_id_rsa" }
      - { source_key: './.ssh/id_rsa', dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa" }
    zoxide_install_temp_folder: '/tmp/zoxide-install.deb'
    ssh_key_dotfiles: "{{ lookup('env', 'HOME') }}/.ssh/ansible_id_rsa" 
  become: true
  become_user: '{{ user }}'
  pre_tasks:
    - name: Update Apt
      become_user: root
      apt:
        force_apt_get: true
        update_cache: true
        state: present 
      tags:
        - install

    - name: Ensure .local/bin is created
      file:
        path: "{{ lookup('env', 'HOME')}}/.local/bin"
        state: directory
        mode: '0755'
      tags:
        - install

  tasks:
    - name: Make sure we have a '{{ user }}' group
      group:
        name: '{{ user }}'
        state: present
      tags:
        - install

    - name: Allow '{{ user }}' group to have passwordless sudo
      become_user: root
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%{{ user }}'
        line: '%{{ user }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
      tags:
        - install

    - include: tasks/ssh-setup.yml
    - include: tasks/dotfiles-setup.yml
    - include: tasks/terraform-setup.yml
    - include: tasks/zoxide-setup.yml
    - include: tasks/core-packages-setup.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/git-setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/npm-packages-setup.yml
