#!/usr/bin/env bash
#sudo apt install software-properties-common
#sudo apt-add-repository --yes --update ppa:ansible/ansible
#sudo apt install ansible
TAGS="$@"


RUN="ansible-playbook local.yml -e user=jmartins -K --ask-vault-pass -vv"

if [[ -z $TAGS ]]; then
$RUN
else
TAGS="${TAGS/ /,}"
RUN="$RUN -t $TAGS"
$RUN
fi

