- name: Cloning .dotfiles
  git:
    repo: 'git@github.com:jmartins-sh/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    key_file: "{{ ssh_key_dotfiles }}"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./ubuntu-install
  tags:
    - install
    - dotfiles
