- name: Ensure .ssh directory exists.
  file:
    dest: "{{ lookup('env', 'HOME') }}/.ssh"
    mode: 0700
    state: directory
- name: Install ssh key
  copy:
    src: "{{ item.source_key }}"
    dest: "{{ item.dest_key }}"
    mode: 0600
  loop:
    "{{ sshs|flatten(levels=1) }}"

- name: Install ssh key public
  copy:
    src: "{{ item.source_key }}.pub"
    dest: "{{ item.dest_key }}.pub"
    mode: 0644
  loop:
    "{{ sshs|flatten(levels=1) }}"

- name: Set authorized key took from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', item.dest_key + '.pub') }}"
      #  with_fileglob:
      #- "{{ lookup('env', 'HOME') }}/.ssh/{{ item.dest_key }}.pub"
  with_items:
    "{{ sshs }}"
